language: latex

services:
  - docker

script:
  - make docker-latexmk

deploy:
  provider: releases
  api_key:
    secure: imhEDT0Q+ncEyovS5ENEl4D6Dki1IAESzzpYYOFEe3YtdBzslPUnldgyUcdyN+uhLL41cdNfmUXz8vd186nqSl65O/caGTACxQOzwwfVk3TFFhU426XX1thsGo4kD4n2bFweyxhUTzM60VxUDF4+9On0tl7sNl64rBGtHEU3Mf5kNLdNblez1OnIF9f30pdIdaATWwfaI7xQw00zBNHuKYvlJ0trturLeuTQR4k4aADkm//O02kKiKCnwtV67V7GCEzJez8XRaiPZVHZA8wBD6/8NLUm4+DonLFAVjOEzg70qdD79+5PoqwDriDh0DwdwQ9fSymEDaP7r8hnZrTv+y+8nqoYDoAfsASTiTwzNE9SPFj+DCAALMMGzJkQMjSN/sbHYMtYkvp03ZXiUqxNeimA2KQZ7/GgHW8D9n/aMJ3UkwShYmgg3f3G0JWL81X9tsn9fgTqEdF3wR4FtkUNnXsmKYrBjNpOcQKOnRq9J1v0Oq3J+8zYiE4C+o1cF/BG1au99YgEva2ZVIvJxRKwjq4H76S2vPyXbwLZjxGTnRcLuYCXYuqG1f05PTF8TbSpQeOhQZHQqNHbcfXpeEnQTTqaGXAqLyK2VAyNzyjeII9hKoMPEoxNBgkd1IM3Bs7adWxbizuTcxU1CFZxncxk7kzmjxG/KCd0cG0B+5VeH8g=
  file: index.pdf
  on:
    tags: true
  skip_cleanup: true
